Basic features: `Vec8f` and `Vec4f`
NamorNiradnug/vector-rust-library pull request #1
Opened 2024-01-03 17:06 UTC by NamorNiradnug

2024-01-04 12:23 UTC, NamorNiradnug commented
CI problem: rust compiler won't tell about missing intrinsics on no-AVX build. Instead it fails to inline those but then successfully links them, resulting AVX instructions working.

2024-01-04 18:30 UTC, asokol123 requested changes

2024-01-04 18:35 UTC, NamorNiradnug commented on src/vec4f.rs
> +        unsafe { *(value as *const Vec4f as *const [f32; 4]) }
`Vecf4` это один `__m128`. Он точно выровнен на `16` байт и содержит 4 float-а, записанных подряд, соответственно каст корректный.

2024-01-04 18:35 UTC, NamorNiradnug commented on src/vec8f.rs
> +#[cfg(avx)]
Тут потому что мне лень писать :)

2024-01-04 18:42 UTC, NamorNiradnug commented on src/vec8f.rs
> +#[cfg(avx)]
> У тебя в этом файле ооочень много таких проверок на `cfg(avx)`
> Может лучше так:
> ```rust
> // vec8f.rs
> #[cfg(avx)]
> mod vec8f_avx;
> #[cfg(avx)]
> pub use vec8f_avx::*;
> 
> #[cfg(not(avx))]
> mod vec8f_noavx;
> #[cfg(not(avx))]
> pub use vec8f_noavx::*;
> ```
> И писать реализацию уже в `vec8f_avx.rs` и `vec8f_noavx.rs`
> Обсуждаемо, но нужны аргументы почему лучше все в одном файле

Я тоже о таком думал, то тогда придется дублировать интерфейс и документацию. Последнее можно избежать, если делать публичные методы общими, а в них вызывать приватные функции, которые и объявлены в платформо-специфисных модулях, но это все равно много кода. Короче мне кажется, что лучше держать имплементации рядом.

2024-01-04 18:46 UTC, NamorNiradnug commented on src/vec4f.rs
> +    xmm: __m128,
я вроде ручками проверил, но да, надо это как-то затестить

2024-01-04 18:51 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub unsafe fn load(addr: *const [f32; 4]) -> Self {
Кажется лучше как раз по дефолту делать unaligned, чтобы пользователю было сложнее ошибиться.

2024-01-04 19:12 UTC, DimaTrushin commented on src/vec4f.rs
> +    pub unsafe fn load(addr: *const [f32; 4]) -> Self {
Тут есть несколько глобальных вопросов:
1) Можем ли мы позволить себе сделать весь интерфейс safe?
Если да, то это очень правильное замечание и нас интересует лишь финальный ассемблер. То есть понять, когда генерится вызов по адресу.
Если нет. То либо надо обе функции иметь либо думать дальше.
2) Даже если мы можем позволить себе safe интерфейс, надо понять что по скорости у safe и unsafe версий. По хорошему надо все версии прочекать на ассемблер и производительность и убедиться, что можно все сделать safe.

2024-01-04 19:15 UTC, DimaTrushin commented on src/vec4f.rs
> +impl From<f32> for Vec4f {
Для не знающих раст. Я правильно понимаю, что этот трейт позволяет неявные преобразования f32 к Vec4f? Или проблема не только в этом или не в этом?

2024-01-04 19:16 UTC, DimaTrushin commented on src/vec4f.rs
> +fn it_works() {
А можешь пояснить, что это значит?

2024-01-04 19:18 UTC, DimaTrushin commented on src/vec8f.rs
> +#[cfg(avx)]
А в оригинале все рядом лежит у Fog-а?

2024-01-04 19:20 UTC, DimaTrushin commented on src/vec4f.rs
> +    xmm: __m128,
По хорошему должен быть файл-интерфейс, который подключает тебе те структуры, которые доступны для текущих флагов компиляции. Ты же можешь делать кросс-компиляцию, когда компилируешь под инструкции, которые на твоей системе не поддерживаются. Но например у программы будет диспетчер в рантайме. Потому обратите внимание не только на проверки текущей машины, а именно на таргет-компиляцию.

2024-01-04 19:22 UTC, DimaTrushin commented on src/vec4f.rs
> +        _mm_loadu_ps(addr as *const f32).into()
Тут стоит поставить какую-нибудь метку, чтобы не забыть, что эта хрень к endianess привязана. Если в будущем будете собирать под более крупный набор инструкций, хер с два вспомните, что это тут было. Нужна какая-то проверка, чтобы упала сборка с ошибкой при попытке скомпилировать под таргет с другим endianess.

2024-01-04 19:32 UTC, asokol123 commented on src/vec4f.rs
> +        unsafe { *(value as *const Vec4f as *const [f32; 4]) }
Мне казалось, что в расте так нельзя без `#[repr(transparent)]`
Завтра скажу точнее

2024-01-04 19:55 UTC, NamorNiradnug commented on src/vec4f.rs
> +    xmm: __m128,
> По хорошему должен быть файл-интерфейс, который подключает тебе те структуры, которые доступны для текущих флагов компиляции. Ты же можешь делать кросс-компиляцию, когда компилируешь под инструкции, которые на твоей системе не поддерживаются. Но например у программы будет диспетчер в рантайме. Потому обратите внимание не только на проверки текущей машины, а именно на таргет-компиляцию.

А, в этом смысле... Я тут всё пишу с мыслью, что у меня есть хотя бы `sse`, и этот модуль в принципе подключается в `#cfg(sse)`, и вроде все инструкции SSE-шные.

Я комментарием в гитхабе писал проблему: нужно как-то проверять, что у меня действительно не используются AVX-фичи на сборке без AVX. Там на все интринзики, конечно, есть `#[target_feature(enable = "avx")]`, но это просто добавляет мне UB в код ¯\_(ツ)_/¯. Как это делать — пока что не знаю. Можете подсказать, если знаете?

2024-01-04 19:58 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub unsafe fn load(addr: *const [f32; 4]) -> Self {
> Тут есть несколько глобальных вопросов:
> 
>     1. Можем ли мы позволить себе сделать весь интерфейс safe?
>        Если да, то это очень правильное замечание и нас интересует лишь финальный ассемблер. То есть понять, когда генерится вызов по адресу.
>        Если нет. То либо надо обе функции иметь либо думать дальше.
> 
>     2. Даже если мы можем позволить себе safe интерфейс, надо понять что по скорости у safe и unsafe версий. По хорошему надо все версии прочекать на ассемблер и производительность и убедиться, что можно все сделать safe.

Мне не нравится идея делать всё safe. Априори будут ситуации, когда safe-интерфейс не даст нужную производительность (скажем, тот же `load_aligned`: в safe-версии такая функция должна проверять, что адрес выравнен и паниковать, если это не так — лишняя проверка).

2024-01-04 20:01 UTC, NamorNiradnug commented on src/vec4f.rs
> +        unsafe { *(value as *const Vec4f as *const [f32; 4]) }
> Мне казалось, что в расте так нельзя без `#[repr(transparent)]` Завтра скажу точнее

Действительно, вроде как нельзя, исправлю.

2024-01-04 20:03 UTC, NamorNiradnug commented on src/vec4f.rs
> +impl From<f32> for Vec4f {
> Для не знающих раст. Я правильно понимаю, что этот трейт позволяет неявные преобразования f32 к Vec4f? Или проблема не только в этом или не в этом?

Не совсем неявные. Работает `1.0.into()` и `Vec4f::from(1.0)`. Если второе еще куда не шло, то первое действительно не очень выразительно.

2024-01-04 20:05 UTC, NamorNiradnug commented on src/vec4f.rs
> +fn it_works() {
> А можешь пояснить, что это значит?

`#[cfg(test)]` будет собирать то, что находится под этим аттрибутом, только при тестировании (`cargo test`; это та самая условная компиляция). То, как написал я, будет собираться в собранной библиотеке даже в `release`.

2024-01-04 20:22 UTC, NamorNiradnug commented on src/vec8f.rs
> +#[cfg(avx)]
> А в оригинале все рядом лежит у Fog-а?

У него реазизация без AVX отдельно, а оптимизации рядом.

2024-01-04 20:37 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub fn load_partial(slice: &[f32]) -> Self {
> А не нарушается ли консистентность с предыдущим комментарием, что нам не нужны unsafe версии с указателями? Или предлагается все версии добавить?

Версии с указателями не могут быть safe по определению. Версии в ссылками — да, но тогда они должны проверять валидность.

2024-01-04 20:44 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub unsafe fn store(&self, addr: *mut [f32; 4]) {
> И почему нет возможности делать `store` по `*mut [f32]`?

Не очень понятно, как это лучше делать. Если такой `store` проверяет, что в слайсе хотя бы `4` элемента, то тогда эта функция бесползна и лучше сделать аналогичную safe-функцию, которая принимает ссылку. Если такой `store` ничего не проверяет, то кажется проще оставить только `store_ptr(addr: *mut [f32; 4])`, и оставить явный каст пользователю.

2024-01-04 20:56 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub fn load_partial(slice: &[f32]) -> Self {
> Хочется еще функцию вида `load(slice: &[f32])`, которая проверяет, что в слайсе ровно 4 элемента, и иначе паникует

Точно ли лучше делать проверку на *ровно* 4, а не *хотя бы* 4?

2024-01-04 20:57 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub fn load_partial(slice: &[f32]) -> Self {
> И можно сделать ее unsafe аналог, который принимает например `*const [f32]`, и загружает, не проверяя количество, а веря что там есть 4

А точно ли есть смысл в этой функции, если есть `load_ptr`?

2024-01-04 21:16 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub fn load_partial(slice: &[f32]) -> Self {
> Хочется еще функцию вида `load(slice: &[f32])`, которая проверяет, что в слайсе ровно 4 элемента, и иначе паникует И можно сделать ее unsafe аналог, который принимает например `*const [f32]`, и загружает, не проверяя количество, а веря что там есть 4

И еще: стоит ли делать такие функции паникующими, или сделать их возвращающими `Option<Self>`?

2024-01-05 13:08 UTC, asokol123 commented on src/vec4f.rs
> +    pub unsafe fn load(addr: *const [f32; 4]) -> Self {
unsafe методы нужны, и это нормально, они есть у любого класса. Делать весь интерфейс safe не нужно никогда.

Но 95% пользователей хотят использовать safe интерфейс, поэтому основные, "красивые" функции хочется иметь safe

2024-01-05 13:09 UTC, asokol123 commented on src/vec4f.rs
> +    pub fn load_partial(slice: &[f32]) -> Self {
Паникующими или возвращающими Option - на твое усмотрение. Я бы паниковал.
Смысл делать когда есть `load_ptr` простой - они safe

2024-01-05 20:25 UTC, NamorNiradnug commented on src/vec4f.rs
> +        _mm_loadu_ps(addr as *const f32).into()
> Угу, я именно про то, что поставить `static_assert(x86 or x86_64)` условно

Всё еще не очень понимаю зачем, если тут в коде `x86`-специфичные интринзики из `std::core::x86[_64]`...

2024-01-06 06:04 UTC, asokol123 commented on src/vec8f.rs
> +                                            ^^^^^^^^^^^^^ won't compile
Это можно заставить комилироваться с `#![feature(generic_const_exprs)]`, но я бы не стал, хочется иметь код, работающий на stable (а пока я nightly не видел, кажется!)
И явно не в этом PR

2024-01-06 06:27 UTC, asokol123 commented on src/vec8f.rs
> +#[cfg(avx)]
Другой вариант, который мне пока нравится больше всего, но потребует больше всего кода:
Сделать три файла:
1) `vec4f.rs`
2) `vec4f_fallback.rs`
3) `vec4f_avx.rs`
В `Vec4f.rs` сделать такое:
```rust
#[cfg(avx)]
mod impl;
#[cfg(not(avx))]
mod impl;

#[repr(transparent)]
struct Vec4f(impl::Vec4f);

impl Vec4f {
    // и тут doc
    pub fn extract(&self, index: usize) -> f32 {
        self.0.extract
    }
}
```

2024-01-06 11:03 UTC, NamorNiradnug commented on src/vec4f.rs
> +    pub fn extract_const<const INDEX: i32>(self) -> f32 {
Потому что интринзик требует `i32`

2024-01-06 11:05 UTC, NamorNiradnug commented on src/vec4f.rs
> +        #[repr(C)]
Тут нельзя: `repr(transparent)` нельзя использовать вместе с `align`

2024-01-06 11:09 UTC, NamorNiradnug commented on src/vec8f.rs
> +    _low: Vec4f,
Потому что есть методы `low` и `high`
Сделать `(Vec4f, Vec4f)` нельзя, т.к. не будет работать `derive(...)`
Сделать нижние почеркивание в конце?

2024-01-06 11:23 UTC, NamorNiradnug commented on src/vec8f.rs
> +    pub unsafe fn load_ptr_aligned(addr: *const [f32; 8]) -> Self {
> Подробнее о том, почему надо брать указатели сразу на весь slice: [блог в ТГ](https://t.me/dereference_pointer_there/6711)

О, на блог Антона я подписан))

2024-01-06 11:53 UTC, NamorNiradnug commented on src/vec4f.rs
> +
Можно реальзовать `Index` и `MutIndex` для `&VecXf`

2024-01-06 12:10 UTC, asokol123 commented on src/vec4f.rs
> +
Там в другом проблема. С `&VecXf` проблемы нет, наш тип по идее Copy вообще.
Проблема в том, что
```rust
trait Index<Idx> {
    type Item;
    fn index(&self, index: Idx) -> &Self::Item; // <- вот в этом & перед Self::Item проблема
}
```

2024-01-06 13:25 UTC, NamorNiradnug commented on src/vec8f.rs
> +                                            ^^^^^^^^^^^^^ won't compile
Эта фича включена, но оно всё равно не компилируется! Уже исправил, чтобы работало на stable

2024-01-06 13:32 UTC, NamorNiradnug commented on src/vec8f.rs
> +    _low: Vec4f,
> Можно иметь методы и поля с одним и тем же названием

Забавно... А как оно работает, если поле `Fn` какой-нибудь имплементирует?

2024-01-06 13:35 UTC, NamorNiradnug commented on src/vec4f.rs
> +
> Там в другом проблема. С `&VecXf` проблемы нет, наш тип по идее Copy вообще. Проблема в том, что
> 
> ```rust
> trait Index<Idx> {
>     type Item;
>     fn index(&self, index: Idx) -> &Self::Item; // <- вот в этом & перед Self::Item проблема
> }
> ```

Я понимаю
Просто для `&VecXf` `index` может возвращать ссылку на кусок соответствующего `xmm`/`ymm`
А вот для `VecXf`, который только значение, и скорее всего находится в регистре, а не в памяти, ссылку на что возвращать непонятно.

2024-01-06 15:36 UTC, NamorNiradnug commented on src/vec4f.rs
> +        unsafe {
Я зачем без sse? Я прогнал под miri, оно не наругалось. Зато нашел другую багу (`as_ptr` вместо `as_mut_ptr`). Надо в CI тоже добавить запуск под miri, но с ним есть проблемы:
 - оно как-то странно работает с `.cargo/config.toml` (но это ладно)
 - оно пока не умеет AVX, но есть [готовый PR](https://github.com/rust-lang/miri/pull/3192)
   - наверное из-за этого `compile_fail`-тесты для `extract_const` компилируются при запуском под `miri`

2024-01-06 21:25 UTC, NamorNiradnug commented on src/vec4f.rs
> +
Я не учел `Index` же `self` по ссылке принимает...
Тогда всё просто :).
Но может быть проблема с производительностью, т.к. использование `index` это гарантированный неявный `store`.

2024-01-06 21:26 UTC, NamorNiradnug commented on src/vec4f.rs
> +
Навееерное можно в теории написать плагин для `clippy`, который будет просить заменить `[]` на `extract`, хотя бы в каких-то простых случаях

2024-01-07 02:56 UTC, NamorNiradnug commented on src/vec8f.rs
> +#[cfg(avx)]
> Другой вариант, который мне пока нравится больше всего, но потребует больше всего кода: Сделать три файла:
> 
>     1. `vec4f.rs`
> 
>     2. `vec4f_fallback.rs`
> 
>     3. `vec4f_avx.rs`
>        В `Vec4f.rs` сделать такое:
> 
> 
> ```rust
> #[cfg(avx)]
> mod impl;
> #[cfg(not(avx))]
> mod impl;
> 
> #[repr(transparent)]
> struct Vec4f(impl::Vec4f);
> 
> impl Vec4f {
>     // и тут doc
>     pub fn extract(&self, index: usize) -> f32 {
>         self.0.extract
>     }
> }
> ```

Осознать, что это действительно лучший способ, было не тривиально...

2024-01-07 05:58 UTC, asokol123 requested changes

2024-01-07 05:58 UTC, asokol123 commented on src/vec4f/mod.rs
> +    #[inline(always)]
Ты уверен что тут нужно именно `inline(always)`?
Я слышал, что его не нужно почти никогда использовать, я бы просто `#[inline]` оставил.
Либо изучить, убедиться в этом и потом прокомментировать.

Почему я считаю, что нужен просто `#[inline]`:
1) он позволит инлайнить даже между крейтами, если llvm так решит
2) __изредка__ бывают ситуации, когда даже такие функции не надо инлайнить. И мы о них не знаем, а разработчики llvm знают

2024-01-07 05:58 UTC, asokol123 commented on src/vec4f/mod.rs
> +        unsafe { self.store_ptr(array.as_mut_ptr()) }
Написать safety comment, хотя бы краткий (можно потом)

2024-01-07 05:58 UTC, asokol123 commented on src/vec4f/mod.rs
> +        // If so, a panicing version should be named `extract_checked` and Fog's version should be
Мне кажется наоборот
В расте принято по дефолту проверять все и быть безопасным. Молча брать `index & 3` конечно лучше для производительности, но сильно усложняет дебаг, и возвращает нас в мир C++, я бы наоборот его версию назвал `extract_wrapping` (посколько `extract_unchecked` - это фунцкия, которая предполагает, что `0 <= index < 8`)

2024-01-07 05:58 UTC, asokol123 commented on src/vec4f/mod.rs
> +        unsafe { *(value as *const Vec4f as *const [f32; 4]) }
Аналогично, к каждому unsafe блоку написать safety comment о том, почему он безопасен

2024-01-07 05:58 UTC, asokol123 commented on src/vec4f/mod.rs
> +        unsafe { &*(self as *const Self as *const f32).add(index) }
Я вот прям почти уверен что тут UB
По сути ты лезешь в кишки структуры стандартной библиотеки без публичных полей.
Сейчас, конечно, оно реализовано как `struct __m128(f32, f32, f32, f32)` ([source](https://doc.rust-lang.org/src/core/stdarch/crates/core_arch/src/x86/mod.rs.html#88)), но
1) в будущем это может измениться
2) даже если не изменится, лезть в приватные поля по сути, еще и брать так ссылку - я бы не стал. Либо надо прям очень качественно убедиться, что это безопасно, либо убрать совсем `impl Index`

2024-01-07 06:03 UTC, asokol123 commented on src/vec8f.rs
> +    _low: Vec4f,
[Вот так](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cf7fec2cc402df29d4816fa2e530cc49)

2024-01-07 08:58 UTC, NamorNiradnug commented on src/vec4f/mod.rs
> +        unsafe { &*(self as *const Self as *const f32).add(index) }
Измениться, мне кажется, это не может, т.к. `__m128` по определению соответствует `xmm`-регистру.

Наличие UB скорее всего отловилось бы Miri, а Miri молчит (см. CI)

2024-01-07 09:03 UTC, NamorNiradnug commented on src/vec4f/mod.rs
> +        unsafe { *(value as *const Vec4f as *const [f32; 4]) }
> Аналогично, к каждому unsafe блоку написать safety comment о том, почему он безопасен

Только к этим или везде?..

2024-01-07 15:26 UTC, asokol123 approved these changes

2024-01-07 15:27 UTC, asokol123 approved these changes

2024-01-07 15:30 UTC, merged