NEON platform support (Arm, aarch64)
NamorNiradnug/vector-rust-library pull request #11
Opened 2024-01-07 12:26 UTC by NamorNiradnug

Closes #7

2024-01-09 10:04 UTC, asokol123 requested changes

2024-01-09 10:04 UTC, asokol123 commented on build.rs
> +        neon: {  target_feature = "neon" }
Давай и тут поставим запятую в конце?

2024-01-09 15:09 UTC, asokol123 commented
Приложи в этот ПР бенчмарки?
Скриншот (а лучше несколько чтобы медленный график не портил масштаб), и комментарии на каком железе и ожидаемы ли результаты

2024-01-09 16:42 UTC, NamorNiradnug commented
[Результата бенчмарка](https://github.com/NamorNiradnug/vector-rust-library/files/13876349/report_arm.tar.gz)
![графичек](https://github.com/NamorNiradnug/vector-rust-library/assets/50048443/069298ce-3b54-42dd-9f94-bb29c7af684f)
На маленьких данных no SIMD версия выигрывает, логично, там скорее всего `load_partial` работает дольше, чем вычисления.
Chunks iterator версия работает медленее, скорее всего либо a) из-за лишних проверок в `Chunks`, либо б) из-за того, что там в цикле не `load_prefix`, а `load_partial`. `load_partial` вероятно работает медленнее, т.к. не за`inline`ен, branch predictor от лишних if-ов спасает. Вероятно совокупность факторов: компилятор не смог заинлайнить и соптимизировать проверку на длину, но надо смотреть ассемблер.
На больших массивах данных (1024 элементов) no SIMD версия примерно в 2 раза быстрее `chunks`, а `chunks` версия примерно в раза быстрее циклов, итого no SIMD в 4 раза медленее. Так и должно быть, т.к. на NEON-е 128-битные регистры.

2024-01-10 09:40 UTC, NamorNiradnug commented
@asokol123 можно мержить?

2024-01-15 08:21 UTC, asokol123 approved these changes

2024-01-15 08:21 UTC, merged