Add more tests
NamorNiradnug/vector-rust-library pull request #17
Opened 2024-01-10 18:41 UTC by NamorNiradnug

2024-01-21 16:38 UTC, asokol123 requested changes

2024-01-21 16:38 UTC, asokol123 commented on tests/generic.rs
> +            #[should_panic]
добавить бы `expected` в `should_panic`

2024-01-21 16:38 UTC, asokol123 commented on tests/generic.rs
> +    (first..first + N).for_each(|i| {
ужас, напиши явный `for i in first..first + N`

2024-01-21 17:15 UTC, NamorNiradnug commented on tests/generic.rs
> +            #[should_panic]
Мм, сложно, там сообщение зависит от `VecXX::N`...

2024-01-22 08:15 UTC, asokol123 approved these changes

2024-01-22 08:35 UTC, merged