Safety comments
NamorNiradnug/vector-rust-library pull request #18
Opened 2024-01-15 22:20 UTC by NamorNiradnug

2024-01-17 09:15 UTC, asokol123 requested changes

2024-01-17 09:15 UTC, asokol123 commented on src/lib.rs
> +#![warn(clippy::undocumented_unsafe_blocks)]
Давай сделаем lint глобальным
Например можно через секцию [lints](https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section) в Cargo.toml

2024-01-17 09:15 UTC, asokol123 commented on src/macros.rs
> +                // SAFETY: the inrinsic won't compile on a platform it isn't available
Точно?
Вроде avx скомпилируется там, где их нет, они требуют только `x86_64`, но не факт что процессор поддерживает avx

2024-01-17 09:15 UTC, asokol123 commented on src/macros.rs
> +                // SAFETY: the inrinsic won't compile on a platform it isn't available
Возможно надо добавить что это гарантируется с помощью cfg_if в build.rs и тем, как мы импортируем интринсики (и убедиться в том, что avx действительно не скомпилируется на старом пентиуме)

2024-01-17 09:15 UTC, asokol123 commented on src/vec4f/neon.rs
> +        // SAFETY: this file is only used on builds with NEON feature
Крайне странно выглядящий комментарий, ты явно хотел что-то другое написать тут

2024-01-17 09:56 UTC, NamorNiradnug commented on src/vec4f/neon.rs
> +        // SAFETY: this file is only used on builds with NEON feature
> Крайне странно выглядящий комментарий, ты явно хотел что-то другое написать тут

ну... там имелось в виду, что оно unsafe, потому что интринзик в `target_feature(enables = "neon")`, а этот код вообще только с неоном бывает... понял, распишу

2024-01-20 19:41 UTC, asokol123 approved these changes

2024-01-20 19:43 UTC, merged