`wide` dotprod benchmark
NamorNiradnug/vector-rust-library pull request #28
Opened 2024-02-15 17:12 UTC by NamorNiradnug

2024-02-16 15:07 UTC, asokol123 requested changes
Результаты в студию!

2024-02-16 15:07 UTC, asokol123 commented on Cargo.toml
> +wide = "0.7"
`features = "std"`
Пока вроде ни на что особо не влияет, и больше на всякий случай

2024-02-16 15:07 UTC, asokol123 commented on Cargo.toml
> +wide = "0.7"
Кстати, можно сделать зависимость опциональной, и активировать только при включении фичи
Тут смысла мало, скорее научиться такое делать просто

2024-02-16 17:07 UTC, NamorNiradnug commented on Cargo.toml
> +wide = "0.7"
dev-dependencies не умеют быть опциональными(

2024-02-17 19:33 UTC, NamorNiradnug commented
[Результаты](https://github.com/NamorNiradnug/vector-rust-library/files/14320014/wide_bench.tar.gz)
![image](https://github.com/NamorNiradnug/vector-rust-library/assets/50048443/cacffa3f-5bcd-47b9-be61-0a7dcd929a31)
На 16ти элементах выглядит так же, как с VCL. Надо ассемблер глянуть.

2024-02-18 09:04 UTC, asokol123 commented
А где сравнение на одном графике твоего кода и wide?
Это будет самый интересный график, остальные там не нужны как раз

2024-02-18 10:05 UTC, NamorNiradnug commented
> А где сравнение на одном графике твоего кода и wide? Это будет самый интересный график, остальные там не нужны как раз

Всм? Тут кроме wide только мой код...

2024-02-18 10:06 UTC, asokol123 commented
А, я глупый
Тогда надо ещё будет разобраться, почему на маленьком числе элементов wide настолько быстрее, да (все, как ты сказал)

А так огонь, PR можно мерджить

2024-02-18 10:06 UTC, asokol123 approved these changes

2024-02-18 10:07 UTC, merged